-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 16:32:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema travel_platform_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travel_platform_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_platform_db` DEFAULT CHARACTER SET utf8 ;
USE `travel_platform_db` ;

-- -----------------------------------------------------
-- Table `travel_platform_db`.`emoloyees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`emoloyees` (
  `SAP_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `e-mail` VARCHAR(255) NOT NULL,
  `dept_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SAP_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_platform_db`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`trips` (
  `trip_id` INT NOT NULL AUTO_INCREMENT,
  `SAP_id` INT NOT NULL,
  `contact_person` VARCHAR(255) NOT NULL,
  `purpose` VARCHAR(255) NOT NULL,
  `place` VARCHAR(255) NOT NULL,
  `start_time` TIME NOT NULL,
  `start_date` DATE NOT NULL,
  `end_time` TIME NOT NULL,
  `end_date` DATE NOT NULL,
  `accomp_person` VARCHAR(255) NOT NULL,
  `currency` VARCHAR(3) NULL,
  `exchange_rate` DOUBLE(12,6) NULL,
  `comments` LONGTEXT NULL,
  `trip_over` TINYINT(1) NULL,
  `trip_estimate` DOUBLE(12,6) NULL,
  PRIMARY KEY (`trip_id`),
  INDEX `SAP_id_idx` (`SAP_id` ASC),
  CONSTRAINT `SAP_id`
    FOREIGN KEY (`SAP_id`)
    REFERENCES `travel_platform_db`.`emoloyees` (`SAP_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_platform_db`.`daily_expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`daily_expenses` (
  `expense_id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `amount` DOUBLE(12,6) NOT NULL,
  PRIMARY KEY (`expense_id`),
  CONSTRAINT `fk_daily_expenses_trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `travel_platform_db`.`trips` (`trip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_platform_db`.`transportation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`transportation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `from` VARCHAR(255) NOT NULL,
  `to` VARCHAR(255) NOT NULL,
  `mileage` INT NULL,
  `amount` DOUBLE(12,6) NULL,
  `airfare` DOUBLE(12,6) NULL,
  `rental_car` DOUBLE(12,6) NULL,
  `bus_train` DOUBLE(12,6) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transportation_trips1_idx` (`trip_id` ASC),
  CONSTRAINT `fk_transportation_trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `travel_platform_db`.`trips` (`trip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_platform_db`.`registration_fees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`registration_fees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `amount` DOUBLE(12,6) NULL,
  `trip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registration_fees_trips1_idx` (`trip_id` ASC),
  CONSTRAINT `fk_registration_fees_trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `travel_platform_db`.`trips` (`trip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_platform_db`.`other_expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`other_expenses` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DOUBLE(12,6) NOT NULL,
  `trip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_other_expenses_trips1_idx` (`trip_id` ASC),
  CONSTRAINT `fk_other_expenses_trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `travel_platform_db`.`trips` (`trip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_platform_db`.`totals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_platform_db`.`totals` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amount` DOUBLE(12,6) NOT NULL,
  `trip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_totals_trips1_idx` (`trip_id` ASC),
  CONSTRAINT `fk_totals_trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `travel_platform_db`.`trips` (`trip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
